### ISSUE TITLE
ParentWindow is null

### ISSUE THREAD

**Issue by olluz** [dojo90/NLogViewer#30]
can you please check if the Parentwindow is null ?

If I add the UserControl as an ElementHost child (e.g. in my Outlook Addin) then it'll throw me an exception, because it is not loaded in a Window...

here:
if (_ParentWindow.FindChildByUid<NLogViewer>(Uid) == null)
and here:
 _ParentWindow.Closed += _ParentWindowOnClosed;

Thanks

**Comment by dojo90** [comment]
Thanks for the hint! This hook was inserted so that the following issue could be solved: Thanks for the hint! This hook was inserted so that the following issue could be solved:

The UserControl is currently disposed of via the _ParentWindow.Closed EventHandler. That would no longer be the case and we would have a memory leak.

If you have a solution for me to solve your problem, I am happy to implement it!

The UserControl is currently disposed of via the Closed EventHandler. That would no longer be the case and we would have a memory leak.

**Comment by olluz** [comment]
I think you had this check before, but removed it for some reason.

May I suggest this simple change:

`
            _ParentWindow = Window.GetWindow(this);

            if (_ParentWindow != null)
            {
                _ParentWindow.Closed += _ParentWindowOnClosed;
            }

            ListView.ScrollToEnd();
`

**Comment by dojo90** [comment]
..and when should `Dispose` (https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer/NLogViewer.xaml.cs#L490) be called?

**Comment by olluz** [comment]
The Unloaded event will still be called. And even though the _ParentWindow below is null it will not throw an exception (which is surprising to me).

`private void _OnUnloaded(object sender, RoutedEventArgs e)
        {
            // look in logical and visual tree if the control has been removed
            if (_ParentWindow.FindChildByUid<NLogViewer>(Uid) == null)
            {
                _Dispose();
            }
        }`

So, Dispose is called in _OnUnloaded.

I don't see any down side in checking if the _ParentWindow is null, because if it is the WindowClosed event will never be called anyway...

**Comment by dojo90** [comment]
> 
> The Unloaded event will still be called. And even though the _ParentWindow below is null it will not throw an exception (which is surprising to me).
>

Since the request is recursive, no exception can be thrown here. See: https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer/Extensions/DependencyObjectExtensions.cs#L20
 
> 
> I don't see any down side in checking if the _ParentWindow is null, because if it is the WindowClosed event will never be called anyway...
>

This logic is needed if you use the `NLogViewer` on a `TabControl` inside of a new `window/popup`. If you change the `TabItem`, the `UnLoaded` handler is called and we need to check if the `popup window` is closed or just another `TabItem` is selected.

Could you please try the following commit whether it solves your problem? https://github.com/dojo90/NLogViewer/commit/92fb12b45dde4c3e4077062814b118a295eac73c

**Comment by dojo90** [comment]
Ah now I think I get it! 🤦‍♂️😂
Since `null` is returned if `_ParentWindow == null` I don't need the `if else` query!

**Comment by olluz** [comment]
yes, that works. Thanks a lot!
