### ISSUE TITLE
Is there a way to adjust or hide the column widths?

### ISSUE THREAD

**Issue by fuyunekojima** [dojo90/NLogViewer#54]
The LoggerName and TimeStamp columns are too wide by default, and I would like to hide them or set the column width to 0.
Is there any other way provided other than modifying the source?

**Comment by dojo90** [comment]
It is currently not planned to adjust the columns. However, we could consider giving the `ListView` (https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer/NLogViewer.xaml#L64) a `Style` from the outside (`DependencyProperty`; there you could then adapt the list as you like) or we could make a `DependencyProperty` to hide each column.

The `ListView` uses an `AutoSizedGridView` (https://github.com/dojo90/NLogViewer/blob/master/src/NLogViewer/Helper/AutoSizedGridView.cs) internally so that the column widths are automatically adjusted. In my opinion it would be more clever to be able to hide the columns. What do you think about this?
